/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.geom.RoundRectangle2D;
import javax.swing.UIManager;
import string_Encrypt_Decrypt.ConvertEncryptDecrypt;

/**
 *
 * @author Admin
 */
public class Page_nhaplieu extends javax.swing.JFrame {
    private String encryptedMsg = null;
    private String decryptedMsg = null;
    /**
     * Creates new form Page_nhaplieu
     */
    public Page_nhaplieu() {
        setUndecorated(true);
        setSize(400, 470);
        setShape(new RoundRectangle2D.Double(0,0, 800, 340, 40, 40));
        setLocationRelativeTo(null);
        initComponents();
        
        
    }
    
    public void thoatAES(){
//        this.setVisible(false);
//        TRANGCHU tc = new TRANGCHU();
//                tc.setVisible(true);
        new TRANGCHU().setVisible(true);
        this.setVisible(false);
         System.out.println(this);
    }

    public void maHoa() {
         encryptedMsg = ConvertEncryptDecrypt.EncryptString(ConvertEncryptDecrypt.plainTextToHexString(txt_PlainText.getText()),
                ConvertEncryptDecrypt.plainTextToHexString(txt_KeyText.getText()));
         
        txt_EncryptedMess.setText(encryptedMsg);
        
        txt_PlainText.setText("");
        
    }
    
    public void giaiMa() {
        decryptedMsg = ConvertEncryptDecrypt.DecryptString(txt_EncryptedMess.getText(),
                ConvertEncryptDecrypt.plainTextToHexString( txt_KeyText.getText()));
        txt_DercyptedMess.setText(ConvertEncryptDecrypt.hexToString(decryptedMsg));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_PlainText = new javax.swing.JTextField();
        txt_KeyText = new javax.swing.JTextField();
        txt_EncryptedMess = new javax.swing.JTextField();
        txt_DercyptedMess = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        panelGradient1 = new GUI.PanelGradient();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_giaiMa = new javax.swing.JButton();
        btn_MaHoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_PlainText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 77, 440, 30));
        getContentPane().add(txt_KeyText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 440, 30));

        txt_EncryptedMess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EncryptedMessActionPerformed(evt);
            }
        });
        getContentPane().add(txt_EncryptedMess, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 440, 30));

        txt_DercyptedMess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DercyptedMessActionPerformed(evt);
            }
        });
        getContentPane().add(txt_DercyptedMess, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 440, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(102, 255, 51));
        jButton1.setText("Reset");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Key text:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Mã hóa AES");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Encrypted message:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Decrypted message:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Plain text");

        btn_giaiMa.setBackground(new java.awt.Color(0, 0, 0));
        btn_giaiMa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_giaiMa.setForeground(new java.awt.Color(255, 255, 255));
        btn_giaiMa.setText("Mã hóa");
        btn_giaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_giaiMaActionPerformed(evt);
            }
        });

        btn_MaHoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_MaHoa.setText("Giải mã");
        btn_MaHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MaHoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient1Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(btn_giaiMa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_MaHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGradient1Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGradient1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelGradient1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient1Layout.createSequentialGroup()
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_giaiMa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_MaHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))))
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 88, Short.MAX_VALUE))
        );

        jPanel1.add(panelGradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_EncryptedMessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EncryptedMessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EncryptedMessActionPerformed

    private void txt_DercyptedMessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DercyptedMessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DercyptedMessActionPerformed

    private void btn_giaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_giaiMaActionPerformed
        maHoa();
    }//GEN-LAST:event_btn_giaiMaActionPerformed

    private void btn_MaHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MaHoaActionPerformed
        giaiMa();
    }//GEN-LAST:event_btn_MaHoaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txt_DercyptedMess.setText("");
        txt_EncryptedMess.setText("");
        txt_PlainText.setText("");
        txt_KeyText.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FlatMacLightLaf.setup();
                UIManager.put( "Button.arc", 20 );
                UIManager.put( "Component.arc", 20 );
                UIManager.put( "ProgressBar.arc", 20 );
                UIManager.put( "TextComponent.arc", 20 );
                Page_nhaplieu page = new Page_nhaplieu();
                page.setLocationRelativeTo(null);
                page.setVisible(true);
            }
        });
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_MaHoa;
    private javax.swing.JButton btn_giaiMa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private GUI.PanelGradient panelGradient1;
    private javax.swing.JTextField txt_DercyptedMess;
    private javax.swing.JTextField txt_EncryptedMess;
    private javax.swing.JTextField txt_KeyText;
    private javax.swing.JTextField txt_PlainText;
    // End of variables declaration//GEN-END:variables
}
