/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.math.BigInteger;
import java.util.Random;
import string_Encrypt_Decrypt.ConvertEncryptDecrypt;

/**
 *
 * @author Admin
 */
public class Page_AES extends javax.swing.JFrame {

    private String encryptedMsg = null;
    private String decryptedMsg = null;

    /**
     * Creates new form Page_RSA
     */
    public Page_AES() {
        initComponents();

    }

    public void maHoa() {
        encryptedMsg = ConvertEncryptDecrypt.EncryptString(ConvertEncryptDecrypt.plainTextToHexString(txt_PlainText.getText()),
                ConvertEncryptDecrypt.plainTextToHexString(txt_KeyText.getText()));

        txt_EncryptedMess.setText(encryptedMsg);
//        System.err.println(encryptedMsg);
        txt_PlainText.setText("");

    }

    public void giaiMa() {
        decryptedMsg = ConvertEncryptDecrypt.DecryptString(txt_EncryptedMess.getText(),
                ConvertEncryptDecrypt.plainTextToHexString(txt_KeyText.getText()));
        txt_DercyptedMess.setText(ConvertEncryptDecrypt.hexToString(decryptedMsg));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Chinh = new javax.swing.JPanel();
        lbl_tieuDe = new javax.swing.JLabel();
        btn_Res = new javax.swing.JButton();
        txt_KeyText = new javax.swing.JTextField();
        lbl_keyPublic = new javax.swing.JLabel();
        txt_PlainText = new javax.swing.JTextField();
        lbl_Plain = new javax.swing.JLabel();
        btn_MaHoa1 = new javax.swing.JButton();
        btn_giaiMa1 = new javax.swing.JButton();
        txt_DercyptedMess = new javax.swing.JTextField();
        txt_EncryptedMess = new javax.swing.JTextField();
        lbl_Encry = new javax.swing.JLabel();
        lbl_Decry = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_tieuDe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_tieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tieuDe.setText("AES");

        btn_Res.setBackground(new java.awt.Color(102, 255, 51));
        btn_Res.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/reset.png"))); // NOI18N
        btn_Res.setText("Reset");
        btn_Res.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResActionPerformed(evt);
            }
        });

        lbl_keyPublic.setText("Key Text:");

        lbl_Plain.setText("Plain text");

        btn_MaHoa1.setBackground(new java.awt.Color(102, 102, 255));
        btn_MaHoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/decrypt.png"))); // NOI18N
        btn_MaHoa1.setText("Giải mã");
        btn_MaHoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MaHoa1ActionPerformed(evt);
            }
        });

        btn_giaiMa1.setBackground(new java.awt.Color(102, 255, 102));
        btn_giaiMa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/encrypt.png"))); // NOI18N
        btn_giaiMa1.setText("Mã hóa");
        btn_giaiMa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_giaiMa1ActionPerformed(evt);
            }
        });

        txt_DercyptedMess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DercyptedMessActionPerformed(evt);
            }
        });

        txt_EncryptedMess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EncryptedMessActionPerformed(evt);
            }
        });

        lbl_Encry.setText("Encrypted message:");

        lbl_Decry.setText("Decrypted message:");

        btn_exit.setBackground(new java.awt.Color(255, 102, 102));
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/exit.png"))); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_ChinhLayout = new javax.swing.GroupLayout(pnl_Chinh);
        pnl_Chinh.setLayout(pnl_ChinhLayout);
        pnl_ChinhLayout.setHorizontalGroup(
            pnl_ChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ChinhLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(pnl_ChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ChinhLayout.createSequentialGroup()
                        .addGroup(pnl_ChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_tieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_ChinhLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lbl_Encry, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_EncryptedMess, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_ChinhLayout.createSequentialGroup()
                                .addGroup(pnl_ChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Decry)
                                    .addComponent(lbl_Plain, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_ChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_ChinhLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txt_DercyptedMess, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnl_ChinhLayout.createSequentialGroup()
                                        .addComponent(txt_PlainText, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(pnl_ChinhLayout.createSequentialGroup()
                                .addComponent(lbl_keyPublic, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_KeyText, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ChinhLayout.createSequentialGroup()
                        .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_giaiMa1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(btn_MaHoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btn_Res, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        pnl_ChinhLayout.setVerticalGroup(
            pnl_ChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ChinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tieuDe)
                .addGap(12, 12, 12)
                .addGroup(pnl_ChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_PlainText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Plain, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnl_ChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_KeyText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_keyPublic, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pnl_ChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_EncryptedMess, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Encry, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnl_ChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_DercyptedMess, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Decry, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(pnl_ChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_giaiMa1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MaHoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Res, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(pnl_Chinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_EncryptedMessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EncryptedMessActionPerformed

    }//GEN-LAST:event_txt_EncryptedMessActionPerformed

    private void txt_DercyptedMessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DercyptedMessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DercyptedMessActionPerformed

    private void btn_giaiMa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_giaiMa1ActionPerformed
        maHoa();
    }//GEN-LAST:event_btn_giaiMa1ActionPerformed

    private void btn_MaHoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MaHoa1ActionPerformed
        giaiMa();
    }//GEN-LAST:event_btn_MaHoa1ActionPerformed

    private void btn_ResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResActionPerformed
        txt_DercyptedMess.setText("");
        txt_EncryptedMess.setText("");
        txt_KeyText.setText("");
        txt_PlainText.setText("");
    }//GEN-LAST:event_btn_ResActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        new TRANGCHU().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Page_RSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Page_RSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Page_RSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Page_RSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Page_RSA().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_MaHoa1;
    private javax.swing.JButton btn_Res;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_giaiMa1;
    private javax.swing.JLabel lbl_Decry;
    private javax.swing.JLabel lbl_Encry;
    private javax.swing.JLabel lbl_Plain;
    private javax.swing.JLabel lbl_keyPublic;
    private javax.swing.JLabel lbl_tieuDe;
    private javax.swing.JPanel pnl_Chinh;
    private javax.swing.JTextField txt_DercyptedMess;
    private javax.swing.JTextField txt_EncryptedMess;
    private javax.swing.JTextField txt_KeyText;
    private javax.swing.JTextField txt_PlainText;
    // End of variables declaration//GEN-END:variables
}
